export { LayoutPipeline } from "./engine.js";
export { breakLines } from "./lineBreaker.js";
export { docToRuns, textToRuns, textblockToRuns } from "./textRuns.js";
export { createNodeRegistry } from "./nodeRegistryBuilder.js";
export { NodeRendererRegistry } from "./nodeRegistry.js";
export { buildPageBoxesFromLines, createPageBoxCollector } from "./pageBoxes.js";
export { buildPageFragmentsFromBoxes, buildPageFragmentsFromLines } from "./pageFragments.js";
export { materializeLayoutGeometry, materializePageGeometry } from "./pageGeometry.js";
export {
  ensureLayoutSettingsPerfState,
  getLayoutSettingsPerfState,
  getLayoutSettingsPerfSummary,
  getLayoutSettingsRuntimeState,
  setLayoutSettingsPerfSummary,
} from "./settingsRuntimeState.js";
export {
  clearPageRenderSignature,
  getLayoutChangeSummary,
  getLayoutGhostTrace,
  getLayoutPaginationDiagnostics,
  getLayoutPerfSummary,
  getLayoutRuntimeMeta,
  getLayoutVersion,
  getLayoutTransportPerf,
  getLayoutWorkerDebug,
  getPageLayoutVersionToken,
  getPageOffsetDelta,
  getPageRenderSignature,
  getPageRenderSignatureVersion,
  getPageRuntimeMeta,
  getPageSourcePageIndex,
  isPageReused,
  isProgressiveLayoutApplied,
  isProgressiveLayoutTruncated,
  markPageReused,
  markPagesReused,
  setLayoutChangeSummary,
  setLayoutForceRedraw,
  setLayoutGhostTrace,
  setLayoutPaginationDiagnostics,
  setLayoutPerfSummary,
  setLayoutVersion,
  setLayoutTransportPerf,
  setLayoutWorkerDebug,
  setPageLayoutVersionToken,
  setPageOffsetDelta,
  setPageRenderSignature,
  setPageRenderSignatureVersion,
  setPageSourcePageIndex,
  setProgressiveLayoutState,
  shouldForceLayoutRedraw,
} from "./runtimeMetadata.js";
export {
  consumeForcedFirstLine,
  materializeSplitResult,
  resolveEmptyVisibleSplitDecision,
  resolveLeafOverflowDecision,
  resolveNormalizedSplitFragments,
  resolveRendererPagination,
  resolveRendererReusePolicy,
  type EmptyVisibleSplitDecision,
  type ForcedFirstLinePlacement,
  type LeafOverflowDecision,
  type MaterializedSplitResult,
  type RendererReusePolicy,
} from "./paginationPolicy.js";
export type {
  LayoutBlockIndexRange,
  LayoutCapabilityFlags,
  LayoutChangeSummary,
  LayoutFromDocOptions,
  LayoutLine,
  LayoutLineBlockAttrs,
  LayoutLineFragmentOwner,
  LayoutPage,
  LayoutPageRuntimeMeta,
  LayoutPerfSummary,
  LayoutPositionRange,
  LayoutResult,
  LayoutResultRuntimeMeta,
  LayoutSettingsLike,
  LayoutSettingsMargin,
  LayoutSettingsPerfState,
  LayoutSettingsRuntimeState,
  LayoutTransportPerf,
  LayoutWorkerDebugInfo,
  TopLevelIndexableDoc,
} from "./engine/types.js";
export type {
  ContainerStyle,
  LayoutBox,
  LayoutFragment,
  LayoutFragmentOwner,
  NodeLayoutContinuation,
  NodeLayoutResult,
  NodeLayoutSplitFragment,
  NodeRenderer,
} from "./nodeRegistry.js";
